{"uuid": "830719ac-35c9-4fdd-b81a-9ee8faf01267", "children": ["a39795c9-e6db-42b4-80ed-eb5e8f55b657", "18685494-81dc-4d7e-874f-b5d6d1f14369", "3ceed119-da61-4368-bdd1-56934481e524", "eb15c84d-bcb0-4077-bf31-1c498fcb3b59"], "befores": [{"name": "start_class_App", "status": "passed", "start": 1649259518132, "stop": 1649259533117}], "afters": [{"name": "start_class_App::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started\n\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 933, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Duixi_Framework_V1\\TestCases\\Test0Welcome\\conftest.py\", line 56, in start_class_App\n    driver.quit()\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1649259610976, "stop": 1649259610994}], "start": 1649259518132, "stop": 1649259610994}