{"uuid": "192357c6-e7ec-4c87-a02c-3c72f33f8f20", "children": ["c5901c1b-178c-48a8-87ee-05823c587014", "26b639d7-6740-42fc-9bdc-55b1d4899ae2", "4e72965e-08af-4c58-9e97-9ffee0f7147c", "f09fcee2-e2ff-4823-804f-142c5ff04216"], "befores": [{"name": "start_class_App", "status": "passed", "start": 1649259361783, "stop": 1649259375940}], "afters": [{"name": "start_class_App::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started\n\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 933, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Duixi_Framework_V1\\TestCases\\Test0Welcome\\conftest.py\", line 56, in start_class_App\n    driver.quit()\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1649259441792, "stop": 1649259441841}], "start": 1649259361783, "stop": 1649259441841}