{"uuid": "84534cf9-028e-4faa-bda7-9a6d9bd84ae1", "children": ["58901ea3-c6cc-4f8b-8cf7-04af83d55f13", "894b5ac4-df7c-4807-968f-7da9d38d3c56", "ae09f1cb-b8b3-4b32-bcac-5b5b144b15b6", "d925f833-509e-4c81-89ee-e9f875371eed"], "befores": [{"name": "startApp", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): 'platformVersion' must be of type string\n\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Duixi_Framework_V1\\TestCases\\Test0Welcome\\conftest.py\", line 33, in startApp\n    driver = baseDriver(noReset=False)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Duixi_Framework_V1\\TestCases\\Test0Welcome\\conftest.py\", line 56, in baseDriver\n    driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', caps)\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 151, in __init__\n    super().__init__(\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1649165353851, "stop": 1649165353914}], "start": 1649165353851, "stop": 1649165354551}