{"uuid": "c90b6d04-dff2-4a3a-b9d8-813d397b78a6", "children": ["86944cda-2916-4257-b6a8-eb017cf49303", "d140b216-7e0e-4b73-970d-9724c16fce12", "720f54d0-d263-4a90-825f-3b0947b78196", "d3d07450-2ab9-40a4-80e6-3fbbb6c45cdf"], "befores": [{"name": "start_class_App", "status": "passed", "start": 1649259752152, "stop": 1649259766406}], "afters": [{"name": "start_class_App::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: A session is either terminated or not started\n\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 933, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Duixi_Framework_V1\\TestCases\\Test0Welcome\\conftest.py\", line 56, in start_class_App\n    driver.quit()\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1649259843736, "stop": 1649259843754}], "start": 1649259752152, "stop": 1649259843755}